<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="fr_CA" sourcelanguage="en_CA">
<context>
    <name>@default</name>
    <message>
        <location filename="../core/services/request_manager.py" line="325"/>
        <source>Error occurred {}</source>
        <translation>Une erreur est survenue {}</translation>
    </message>
</context>
<context>
    <name>ActionDialog</name>
    <message>
        <location filename="../ui/py_files/action_dialog.py" line="77"/>
        <source>Action canceled</source>
        <translation>Action Annulée</translation>
    </message>
    <message>
        <location filename="../ui/py_files/action_dialog.py" line="82"/>
        <source>Cancel</source>
        <translation>Annuler</translation>
    </message>
    <message>
        <location filename="../ui/py_files/action_dialog.py" line="92"/>
        <source>Close</source>
        <translation>Fermer</translation>
    </message>
</context>
<context>
    <name>ConnectionDialog</name>
    <message>
        <location filename="../ui/py_files/connection_dialog.py" line="128"/>
        <source>logout</source>
        <translation>Déconnection</translation>
    </message>
    <message>
        <location filename="../ui/py_files/connection_dialog.py" line="82"/>
        <source>login</source>
        <translation>Connection</translation>
    </message>
    <message>
        <location filename="../ui/py_files/connection_dialog.py" line="93"/>
        <source>Welcome {}&lt;br /&gt;</source>
        <translation>Bienvenue {}&lt;br/&gt;</translation>
    </message>
    <message>
        <location filename="../ui/py_files/connection_dialog.py" line="110"/>
        <source>no organization found</source>
        <translation>Aucune organisation trouvée</translation>
    </message>
    <message>
        <location filename="../ui/py_files/connection_dialog.py" line="113"/>
        <source>Authentication expired</source>
        <translation>Authentification expiré</translation>
    </message>
    <message>
        <location filename="../ui/py_files/connection_dialog.py" line="133"/>
        <source>Authentication error</source>
        <translation>Erreur D'authentification</translation>
    </message>
    <message>
        <location filename="../ui/py_files/connection_dialog.py" line="96"/>
        <source>
Connected to: {}</source>
        <translation>
Connecté à: {}</translation>
    </message>
</context>
<context>
    <name>ConvertLayersToZipTask</name>
    <message>
        <location filename="../core/tasks/write_layer_tasks.py" line="55"/>
        <source>Layer {} of type {} is not supported for export</source>
        <translation>La couche {} de type {} n'est pas supportée pour l'exportation</translation>
    </message>
    <message>
        <location filename="../core/tasks/write_layer_tasks.py" line="69"/>
        <source>Error writing layer for layer {}: {}</source>
        <translation>Erreur lors de l'écriture de la couche {}: {}</translation>
    </message>
    <message>
        <location filename="../core/tasks/write_layer_tasks.py" line="109"/>
        <source>Error writing layer &apos;{}&apos;: unknown layer type</source>
        <translation>Erreur lors de l'écriture de la couche '{}': Type de couche inconnu</translation>
    </message>
    <message>
        <location filename="../core/tasks/write_layer_tasks.py" line="147"/>
        <source>Error writing layer {}: zip raster not supported</source>
        <translation>Erreur lors de l'écriture de la couche {}: les couches rasters compressées (zip) ne sont pas supportées</translation>
    </message>
    <message>
        <location filename="../core/tasks/write_layer_tasks.py" line="236"/>
        <source>Missing required files for {}: {}</source>
        <translation>Des fichiers sont manquant pour les couches {}: {}</translation>
    </message>
    <message>
        <location filename="../core/tasks/write_layer_tasks.py" line="310"/>
        <source>Unsupported file type {} for layer {}</source>
        <translation>Type de fichier {} non supporté pour la couche {}</translation>
    </message>
    <message>
        <location filename="../core/tasks/write_layer_tasks.py" line="315"/>
        <source>Unsupported layer: {} ({}), the provider is not supported</source>
        <translation>Couche {} ({}) non supporté, le fournisseur n'est pas supporté</translation>
    </message>
</context>
<context>
    <name>CreateJMCProjectTask</name>
    <message>
        <location filename="../core/tasks/create_jmc_project_task.py" line="69"/>
        <source>Error creating project : {}</source>
        <translation>Erreur lors de la creation du projet: {}</translation>
    </message>
    <message>
        <location filename="../core/tasks/create_jmc_project_task.py" line="133"/>
        <source>Error creating labeling for layer {}, JMap Cloud only support single rule labeling</source>
        <translation>Erreur lors de la creation de l'étiquetage pour la couche {}: JMap Cloud ne supporte que les règles uniques d'étiquetage.</translation>
    </message>
</context>
<context>
    <name>CustomQgsTask</name>
    <message>
        <location filename="../core/tasks/custom_qgs_task.py" line="46"/>
        <source>{} was canceled</source>
        <translation>{} a été annulé(e)</translation>
    </message>
    <message>
        <location filename="../core/tasks/custom_qgs_task.py" line="51"/>
        <source>{} completed successfully</source>
        <translation>{} été complété(e) avec succès</translation>
    </message>
    <message>
        <location filename="../core/tasks/custom_qgs_task.py" line="56"/>
        <source>
                        {} not successful but without 
                        exception (probably the task was manually 
                        canceled by the user)
                        </source>
        <translation>                        {} ne s'est pas complété avec succès, mais sans
                        exceptions (La tâche à probablement été 
                        annulée par l'utilisateur)
                        </translation>
    </message>
</context>
<context>
    <name>CustomTaskManager</name>
    <message>
        <location filename="../core/tasks/custom_qgs_task.py" line="145"/>
        <source>{} was canceled</source>
        <translation>{} a été annulé(e)</translation>
    </message>
    <message>
        <location filename="../core/tasks/custom_qgs_task.py" line="169"/>
        <source>
                        {} not successful but without 
                        exception (probably the task was manually 
                        canceled by the user)
                        </source>
        <translation>                        {} ne s'est pas complété avec succès, mais sans
                        exceptions (La tâche à probablement été 
                        annulée par l'utilisateur)
                        </translation>
    </message>
</context>
<context>
    <name>DatasourceManager</name>
    <message>
        <location filename="../core/services/files_manager.py" line="297"/>
        <source>Creating datasources</source>
        <translation>Création de sources de données</translation>
    </message>
    <message>
        <location filename="../core/services/files_manager.py" line="385"/>
        <source>Server is analyzing datasources</source>
        <translation>Le serveur analyse les sources de données</translation>
    </message>
    <message>
        <location filename="../core/services/files_manager.py" line="391"/>
        <source>Unknown error : {}</source>
        <translation>Un erreur inconnue s'est produit: {}</translation>
    </message>
    <message>
        <location filename="../core/services/files_manager.py" line="395"/>
        <source>JMap server error : {}</source>
        <translation>Erreur du serveur JMap: {}</translation>
    </message>
</context>
<context>
    <name>Dialog</name>
    <message>
        <location filename="../ui/py_files/action_dialog_base_ui.py" line="74"/>
        <source>Action</source>
        <translation>Action</translation>
    </message>
    <message>
        <location filename="../ui/py_files/warning_dialog_base_ui.py" line="56"/>
        <source>Close</source>
        <translation>Fermer</translation>
    </message>
    <message>
        <location filename="../ui/py_files/connection_dialog_base_ui.py" line="95"/>
        <source>Connection to JMap Cloud</source>
        <translation>Connexion à JMap Cloud</translation>
    </message>
    <message>
        <location filename="../ui/py_files/connection_dialog_base_ui.py" line="96"/>
        <source>Email : </source>
        <translation>Email</translation>
    </message>
    <message>
        <location filename="../ui/py_files/connection_dialog_base_ui.py" line="97"/>
        <source>Password :</source>
        <translation>Mot de passe</translation>
    </message>
    <message>
        <location filename="../ui/py_files/connection_dialog_base_ui.py" line="98"/>
        <source>login</source>
        <translation>Connexion</translation>
    </message>
    <message>
        <location filename="../ui/py_files/connection_dialog_base_ui.py" line="99"/>
        <source>Choose organization :</source>
        <translation>Choisissez une organisation</translation>
    </message>
    <message>
        <location filename="../ui/py_files/connection_dialog_base_ui.py" line="100"/>
        <source>OK</source>
        <translation>OK</translation>
    </message>
    <message>
        <location filename="../ui/py_files/export_project_dialog_base_ui.py" line="93"/>
        <source>Export project</source>
        <translation>Exporter un projet</translation>
    </message>
    <message>
        <location filename="../ui/py_files/export_project_dialog_base_ui.py" line="94"/>
        <source>Export a project to JMap Cloud</source>
        <translation>Exporter un projet vers JMap Cloud</translation>
    </message>
    <message>
        <location filename="../ui/py_files/export_project_dialog_base_ui.py" line="95"/>
        <source>Project title :</source>
        <translation>Titre du projet</translation>
    </message>
    <message>
        <location filename="../ui/py_files/export_project_dialog_base_ui.py" line="96"/>
        <source>Export</source>
        <translation>Exporter</translation>
    </message>
    <message>
        <location filename="../ui/py_files/open_project_dialog_base_ui.py" line="66"/>
        <source>Open project</source>
        <translation>Ouvrir un projet</translation>
    </message>
    <message>
        <location filename="../ui/py_files/open_project_dialog_base_ui.py" line="67"/>
        <source> Vector layer type :</source>
        <translation>Type de couche vectorielle</translation>
    </message>
    <message>
        <location filename="../ui/py_files/open_project_dialog_base_ui.py" line="68"/>
        <source>Default</source>
        <translation>Par défaut</translation>
    </message>
    <message>
        <location filename="../ui/py_files/open_project_dialog_base_ui.py" line="69"/>
        <source>All in GeoJSON</source>
        <translation>En GeoJSON</translation>
    </message>
    <message>
        <location filename="../ui/py_files/open_project_dialog_base_ui.py" line="70"/>
        <source>All in Vector Tiles</source>
        <translation>En tuiles vectorielles</translation>
    </message>
    <message>
        <location filename="../ui/py_files/warning_dialog_base_ui.py" line="45"/>
        <source>Warning</source>
        <translation>Avertissement</translation>
    </message>
    <message>
        <location filename="../ui/ui_files/warning_dialog_base.ui" line="62"/>
        <source>&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0//EN&quot; &quot;http://www.w3.org/TR/REC-html40/strict.dtd&quot;&gt;
&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;style type=&quot;text/css&quot;&gt;
p, li { white-space: pre-wrap; }
&lt;/style&gt;&lt;/head&gt;&lt;body style=&quot; font-family:&apos;MS Shell Dlg 2&apos;; font-size:7.8pt; font-weight:400; font-style:normal;&quot;&gt;
&lt;p align=&quot;center&quot; style=&quot;-qt-paragraph-type:empty; margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;br /&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>ExportLayerStyleTask</name>
    <message>
        <location filename="../core/tasks/export_layer_style_task.py" line="202"/>
        <source>Error for layer {}. Renderer type {}, not supported</source>
        <translation>Erreur pour la couche {}: Le type du moteur de rendu {} n'est pass supporté.</translation>
    </message>
    <message>
        <location filename="../core/tasks/export_layer_style_task.py" line="261"/>
        <source>Unexpected rule &apos;{}&apos; have symbol but no parent rule were found</source>
        <translation>La règle'{}' est invalide, car elle possède un symbole, mais pas de règle parent.</translation>
    </message>
    <message>
        <location filename="../core/tasks/export_layer_style_task.py" line="339"/>
        <source>invalid expression &apos;{}&apos;, too many or no valid operators</source>
        <translation>Expression '{}' invalide: L'expression a trop ou pas assez d'opérateurs.</translation>
    </message>
    <message>
        <location filename="../core/tasks/export_layer_style_task.py" line="349"/>
        <source>error in expression &apos;{}&apos;. &apos;OR&apos; operator not supported in JMap Cloud</source>
        <translation>Erreur dans l'expression '{}': L'opérateur 'OR' n'est pas supporté dans JMap Cloud.</translation>
    </message>
    <message>
        <location filename="../core/tasks/export_layer_style_task.py" line="358"/>
        <source>invalid expression &apos;{}&apos;</source>
        <translation>L'experssion '{}' est invalide.</translation>
    </message>
    <message>
        <location filename="../core/tasks/export_layer_style_task.py" line="364"/>
        <source>invalid operator {} in expression &apos;{}&apos;</source>
        <translation>L'opérateur '{}' est invalide dans l'expression '{}'.</translation>
    </message>
    <message>
        <location filename="../core/tasks/export_layer_style_task.py" line="372"/>
        <source>invalid attribute in expression &apos;{}&apos;. Attributes: not in fileds : {}</source>
        <translation>Attribut invalide dans l'expression '{}': L'attribut n'existe pas dans: {}.</translation>
    </message>
    <message>
        <location filename="../core/tasks/export_layer_style_task.py" line="382"/>
        <source>invalid value {} in expression &apos;{}&apos; </source>
        <translation>Valeur '{}' invalide dans l'expression '{}'.</translation>
    </message>
    <message>
        <location filename="../core/tasks/export_layer_style_task.py" line="421"/>
        <source>Export style error for layer &apos;{}&apos;. Unsupported symbol layer</source>
        <translation>Erreur lors de l'exportation de style pour la couche '{}': Une couche de symbole est invalide.</translation>
    </message>
    <message>
        <location filename="../core/tasks/export_layer_style_task.py" line="443"/>
        <source>Export style error: {}</source>
        <translation>Erreur lors de l'exportation de style: '{}'.</translation>
    </message>
    <message>
        <location filename="../core/tasks/export_layer_style_task.py" line="453"/>
        <source>Error exporting style rule for layer &apos;{}&apos;: no condition in style rule to export with</source>
        <translation>Une erreur est survenue lors de l'exportation des règles de style pour la couche '{}': Aucune condition dans la règle à exporter.</translation>
    </message>
    <message>
        <location filename="../core/tasks/export_layer_style_task.py" line="511"/>
        <source>Error getting style for layer &apos;{}&apos;: {}</source>
        <translation>Erreur lors de la récupération des style pour la couche '{}': {}</translation>
    </message>
    <message>
        <location filename="../core/tasks/export_layer_style_task.py" line="520"/>
        <source>Error patching style for layer &apos;{}&apos;: {}</source>
        <translation>Erreur lors de la modification des style pour la couche '{}': {}.</translation>
    </message>
</context>
<context>
    <name>ExportProjectDialog</name>
    <message>
        <location filename="../ui/py_files/export_project_dialog.py" line="43"/>
        <source>Project title needed</source>
        <translation>Titre du projet obligatoire</translation>
    </message>
</context>
<context>
    <name>ExportProjectManager</name>
    <message>
        <location filename="../core/services/export_project_manager.py" line="62"/>
        <source>Initializing loading</source>
        <translation>Initialisation du chargement</translation>
    </message>
    <message>
        <location filename="../core/services/export_project_manager.py" line="63"/>
        <source>&lt;h3&gt;Project exportation canceled&lt;/h3&gt;</source>
        <translation>&lt;h3&gt;Exportation du projet annulé&lt;/h3&gt;</translation>
    </message>
    <message>
        <location filename="../core/services/export_project_manager.py" line="75"/>
        <source>Converting layers to zip</source>
        <translation>Compression des couches</translation>
    </message>
    <message>
        <location filename="../core/services/export_project_manager.py" line="81"/>
        <source>convert layer to zip</source>
        <translation>Compression des couches</translation>
    </message>
    <message>
        <location filename="../core/services/export_project_manager.py" line="99"/>
        <source>Uploading layers files</source>
        <translation>Exportation des fichiers de couches</translation>
    </message>
    <message>
        <location filename="../core/services/export_project_manager.py" line="101"/>
        <source>Upload layer files</source>
        <translation>Exportation des fichiers de couches</translation>
    </message>
    <message>
        <location filename="../core/services/export_project_manager.py" line="122"/>
        <source>Creating datasources</source>
        <translation>Creation des sources de données</translation>
    </message>
    <message>
        <location filename="../core/services/export_project_manager.py" line="125"/>
        <source>Create datasource</source>
        <translation>Creation des sources de données</translation>
    </message>
    <message>
        <location filename="../core/services/export_project_manager.py" line="146"/>
        <source>Creating JMap Cloud project</source>
        <translation>Creation du projet JMap Cloud</translation>
    </message>
    <message>
        <location filename="../core/services/export_project_manager.py" line="149"/>
        <source>Create JMap Cloud project</source>
        <translation>Creation du projet JMap Cloud</translation>
    </message>
    <message>
        <location filename="../core/services/export_project_manager.py" line="168"/>
        <source>Exporting layer styles</source>
        <translation>Exportation des styles des couches</translation>
    </message>
    <message>
        <location filename="../core/services/export_project_manager.py" line="186"/>
        <source>{} in task {} for layer {}</source>
        <translation>{} dans la tâche {} pour la couche {}</translation>
    </message>
    <message>
        <location filename="../core/services/export_project_manager.py" line="193"/>
        <source>{} in task {} for layer {} with file {}
</source>
        <translation>{} dans la tâche {} pour la couche {} pour le fichier {}</translation>
    </message>
    <message>
        <location filename="../core/services/export_project_manager.py" line="213"/>
        <source>&lt;h3&gt;Project exportation finished&lt;3&gt;</source>
        <translation>&lt;h3&gt;Exportation du projet complétée&lt;/h3&gt;</translation>
    </message>
    <message>
        <location filename="../core/services/export_project_manager.py" line="215"/>
        <source>&lt;h4&gt;Some errors occurred during the process:&lt;/h4&gt;</source>
        <translation>&lt;h4&gt;Des erreurs se sont produits pendant le processus:&lt;/h4&gt;</translation>
    </message>
</context>
<context>
    <name>ImportProjectManager</name>
    <message>
        <location filename="../core/services/import_project_manager.py" line="101"/>
        <source>Initializing loading</source>
        <translation>Initialisation du chargement</translation>
    </message>
    <message>
        <location filename="../core/services/import_project_manager.py" line="103"/>
        <source>&lt;h3&gt;Project importation canceled&lt;/h3&gt;</source>
        <translation>&lt;h3&gt;Importation du projet annulée&lt;/h3&gt;</translation>
    </message>
    <message>
        <location filename="../core/services/import_project_manager.py" line="173"/>
        <source>Checking project data</source>
        <translation>Vérification des données du projet</translation>
    </message>
    <message>
        <location filename="../core/services/import_project_manager.py" line="189"/>
        <source>error formatting properties</source>
        <translation>Erreu lors du formatage des données</translation>
    </message>
    <message>
        <location filename="../core/services/import_project_manager.py" line="202"/>
        <source>Loading project layers...</source>
        <translation>Chargement des couches du projet...</translation>
    </message>
    <message>
        <location filename="../core/services/import_project_manager.py" line="260"/>
        <source>Unknown error when loading vector layer : {}</source>
        <translation>Erreur inconnue lors du chargement de la couche vectorielle '{}'</translation>
    </message>
    <message>
        <location filename="../core/services/import_project_manager.py" line="266"/>
        <source>Unsupported layer {} of type {}</source>
        <translation>Couche '{}' de type '{}' non supportée</translation>
    </message>
    <message>
        <location filename="../core/services/import_project_manager.py" line="285"/>
        <source>Error getting Layer {}</source>
        <translation>Erreur lors de la récupération de couche {}</translation>
    </message>
    <message>
        <location filename="../core/services/import_project_manager.py" line="293"/>
        <source>Layer {} is not a valid wms layer</source>
        <translation>La couche '{}' n'est pas un couche WMS valide</translation>
    </message>
    <message>
        <location filename="../core/services/import_project_manager.py" line="400"/>
        <source>Layer {} is not valid</source>
        <translation>La couche '{}' n'est pas valide</translation>
    </message>
    <message>
        <location filename="../core/services/import_project_manager.py" line="424"/>
        <source>Loading layer groups</source>
        <translation>chargement du groupement des couches</translation>
    </message>
    <message>
        <location filename="../core/services/import_project_manager.py" line="434"/>
        <source>Loading layer order</source>
        <translation>Chargement de l'ordre des couches</translation>
    </message>
    <message>
        <location filename="../core/services/import_project_manager.py" line="490"/>
        <source>&lt;h1&gt;Warning&lt;/h1&gt;</source>
        <translation>&lt;h1&gt;Avertissement&lt;/h1&gt;</translation>
    </message>
    <message>
        <location filename="../core/services/import_project_manager.py" line="490"/>
        <source>&lt;p&gt;You don&apos;t have all the right to edit this layer&lt;/p&gt;</source>
        <translation>&lt;p&gt;Vous n'avez pas toutes les permissions pour éditer cette couche&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../core/services/import_project_manager.py" line="490"/>
        <source>&lt;p&gt;Some changes made on this layer may not be pushed to the JMap Cloud project&lt;/p&gt;</source>
        <translation>&lt;p&gt;Certains changements apporté à cette couche ne seront pas publié dans JMap Cloud&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../core/services/import_project_manager.py" line="490"/>
        <source>&lt;p&gt;Here are the rights you have on this layer:&lt;/p&gt;&lt;br&gt;</source>
        <translation>&lt;p&gt;Voici les droits que vous avez sur cette couche:&lt;/p&gt;&lt;br&gt;</translation>
    </message>
    <message>
        <location filename="../core/services/import_project_manager.py" line="554"/>
        <source>Finalization...</source>
        <translation>Finalisation...</translation>
    </message>
    <message>
        <location filename="../core/services/import_project_manager.py" line="556"/>
        <source>&lt;h3&gt;Project loaded successfully&lt;/h3&gt;</source>
        <translation>&lt;h3&gt;Projet importé avec succès&lt;/h3&gt;</translation>
    </message>
    <message>
        <location filename="../core/services/import_project_manager.py" line="561"/>
        <source>&lt;h4&gt;Warning&lt;/h4&gt;</source>
        <translation>&lt;h4&gt;Avertissement&lt;/h4&gt;</translation>
    </message>
    <message>
        <location filename="../core/services/import_project_manager.py" line="561"/>
        <source>&lt;p&gt;The JMap Cloud project crs is different from the actual crs of the project&lt;/p&gt;</source>
        <translation>&lt;p&gt;Le crs du projet JMap Cloud est différent du crs actuel du projet&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../core/services/import_project_manager.py" line="561"/>
        <source>&lt;p&gt;The crs set in JMap Cloud project is : {}&lt;/p&gt;</source>
        <translation>&lt;p&gt;Le crs du projet JMap Cloud est: {}&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../core/services/import_project_manager.py" line="568"/>
        <source>&lt;h4&gt;Some errors occurred during the import:&lt;/h4&gt;</source>
        <translation>&lt;h4&gt;Des erreurs se sont produites pendant l'importation&lt;/h4&gt;</translation>
    </message>
    <message>
        <location filename="../core/services/import_project_manager.py" line="314"/>
        <source>Layer {} is not a valid wmts layer</source>
        <translation>La couche '{}' n'est pas une couche WMTS valide</translation>
    </message>
</context>
<context>
    <name>JMapAuth</name>
    <message>
        <location filename="../core/services/auth_manager.py" line="204"/>
        <source>Logout Error</source>
        <translation>Erreur de déconnexion</translation>
    </message>
</context>
<context>
    <name>JMapCloud</name>
    <message>
        <location filename="../jmap_cloud.py" line="164"/>
        <source>Connection</source>
        <translation>Connexion</translation>
    </message>
    <message>
        <location filename="../jmap_cloud.py" line="169"/>
        <source>Open project</source>
        <translation>Ouvrir un projet</translation>
    </message>
    <message>
        <location filename="../jmap_cloud.py" line="174"/>
        <source>Export project</source>
        <translation>Exporter un projet</translation>
    </message>
    <message>
        <location filename="../jmap_cloud.py" line="179"/>
        <source>Refresh token</source>
        <translation>Rafraichir le token</translation>
    </message>
</context>
<context>
    <name>OpenProjectDialog</name>
    <message>
        <location filename="../ui/py_files/open_project_dialog.py" line="48"/>
        <source>loading...</source>
        <translation>Chargement...</translation>
    </message>
    <message>
        <location filename="../ui/py_files/open_project_dialog.py" line="58"/>
        <source>Error loading projects, please try again</source>
        <translation>Erreur lors du chargement des projets. Veuillez réessayer</translation>
    </message>
    <message>
        <location filename="../ui/py_files/open_project_dialog.py" line="107"/>
        <source>No project found</source>
        <translation>Aucun projet trouvé</translation>
    </message>
</context>
<context>
    <name>compressFilesToZipTask</name>
    <message>
        <location filename="../core/tasks/write_layer_tasks.py" line="369"/>
        <source>Converting layers to zip</source>
        <translation>Compression des couches</translation>
    </message>
    <message>
        <location filename="../core/tasks/write_layer_tasks.py" line="390"/>
        <source>Error: {} is not a valid file or folder.</source>
        <translation>Erreur: {} N'est pas un fichier ou un dossier valide</translation>
    </message>
</context>
</TS>
